### ISSUE TITLE
complete example Wikipedia gene page driven by wikidata

### ISSUE THREAD

**Issue by goodb** [SuLab/genewiki#13]
Use a gene that has both a pdb image and a gene atlas image so we can demo the whole thing.

**Comment by julialturner** [comment]
These are the items I would like to complete before moving on to another gene.
1. GO links
2. UCSC url working correctly
Once these are done then I can start on an additional gene. These items also should be added as new features to the infobox:
1. Expandable lists for RefSeq ID
2.  Edit links for directly accessing the wikidata

**Comment by goodb** [comment]
This is done.  See Reelin article as of today.  Many other genes will work when you put {{infobox gene}} on them.  Broad roll out awaiting newer all-lua version with better error handling.
