### ISSUE TITLE
update index after article creation

### ISSUE THREAD

**Issue by andrewsu** [SuLab/genewiki#4]
Previously I created the Gene Wiki page for ACADM (https://en.wikipedia.org/wiki/ACADM) using the page creation tool.  The mapping service (http://genewiki.sulab.org/map/wiki/34/) should now return a redirect to the WP page, but still goes to the article creation page:

**Comment by julialturner** [comment]
part of the ~109 that are in the infobox list, but no mapping was created for it

**Comment by andrewsu** [comment]
this one now appears to be fixed.  I just created https://en.wikipedia.org/wiki/Template:PBB/159091 and https://en.wikipedia.org/wiki/FAM122C using the article creation tool, and now the redirect from http://genewiki.sulab.org/map/wiki/159091 works fine.
