### ISSUE TITLE
if image already exists, do not update

### ISSUE THREAD

**Issue by andrewsu** [SuLab/genewiki#6]
example edit to avoid: https://en.wikipedia.org/w/index.php?title=Template%3APBB%2F23405&type=revision&diff=670593763&oldid=647031935

**Comment by julialturner** [comment]
Code checks for image and if it exists it doesn't update

**Comment by julialturner** [comment]
*fix: b80c70822bb15cd0878e4dfc6ca47ae9005f3b1a
*fix: c2087d838c67e8df4f59f50dab30a04bcecb25fe
