### ISSUE TITLE
creation tool incorrectly reporting "Invalid or missing Entrez Identifier"

### ISSUE THREAD

**Issue by andrewsu** [SuLab/genewiki#9]
This page reports an error "Invalid or missing Entrez Identifier"

http://genewiki.sulab.org/wiki/article/create/28699/

But 28699 is a valid Entrez Gene ID:

http://www.ncbi.nlm.nih.gov/gene/28699/

**Comment by julialturner** [comment]
* 7f7e5f10dcf5362d15d95e1d5fda7433af6b68f5
